import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ProducDesk from '../public/image-product-desktop.jpg'
import ProducMob from "../public/image-product-mobile.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-red-100 h-screen w-screen">

      <div className=' p-6'>
            <Image className='rounded-t-xl' src={ProducMob} alt='Perfume Channel'/>
          <section className='rounded-b-xl bg-white p-5 '> 
        <div  >
            <h1 className='text-gray-500 text-sm tracking-widest '>PERFUME</h1>
            <h1 className=' text-4xl my-3 font-serif font-extrabold '>Gabrielle Essence Eau De Parfum</h1>
            <p className='text-gray-500  text-lg py-2  tracking-widest '>A floral, solar and voluptuous interpretation composed by Olivier Polge, 
            Perfumer-Creator for the House of CHANEL.</p>
        </div>
        <div>
        <div className='flex  items-center'>
            <h1 className='text-green-800 text-3xl font-bold font- '>$149.99</h1>
            <h4 className='mx-3 text-gray-600  line-through '>$169.99</h4>
        </div>
        <div className='flex justify-center'>
        <button className= 'btn my-3'> Add to Cart</button>
        </div>
        </div>

      </section>
      </div>
      
      </main>
    </>
  )
}
