import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ProducDesk from '../public/image-product-desktop.jpg'
import ProducMob from "../public/image-product-mobile.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-red-100 m-4">
  
      <Image src={ProducMob}/>
      <section className=' bg-red-100 m-4 '> 
        <div>
          <h1 className=' text-gray-500 text-sm tracking-widest '>PERFUME</h1>

          <h1 className=' text-3xl'>Gabrielle Essence Eau De Parfum</h1>

          <p>A floral, solar and voluptuous interpretation composed by Olivier Polge, 
          Perfumer-Creator for the House of CHANEL.</p>
        </div>
        <div>
          <h1>$149.99</h1>
          <h4>$169.99</h4>

        </div>

        <div>
        <button className='bg-teal-800 py-2 px-9 rounded-md text-white'> Add to Cart</button>
        </div>

      </section>
      
      </main>
    </>
  )
}
