import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ProducDesk from '../public/image-product-desktop.jpg'
import ProducMob from "../public/image-product-mobile.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-red-100 h-screen w-screen">

      <div className=' max-h-mid max-w-mid m-auto px-6 py-10 flex flex-col md:flex-row max-w-sm'>
              <Image className='h-full w-full rounded-t-lg block md:hidden md:rounded-l-xl ' src={ProducMob} alt='Perfume Channel'/>
              <Image className='h-full w-full  hidden md:block rounded-l-xl' src={ProducDesk} alt='Perfume Desk Channel'/>          
        <section className='rounded-b-lg bg-white p-5  md:flex flex-col justify-around rounded-r-lg rounded-l-none  '> 
        <div> 
              <h1 className='text-gray-500 text-sm tracking-widest  md:text-xs '>PERFUME</h1>
              <h1 className=' text-3xl my-3 font-serif font-extrabold md:text-'>Gabrielle Essence Eau De Parfum</h1>
              <p className='text-gray-500  text-sm py-1  leading-6 tracking-widest  md:text-sm '>A floral, solar and voluptuous interpretation composed by Olivier Polge, 
              Perfumer-Creator for the House of CHANEL.</p>
        </div>
        <div> 
          <div className='flex  items-center'>
              <h1 className='text-teal-700 text-3xl py-2 font-bold font- '>$149.99</h1>
              <h4 className='mx-3 text-gray-600  line-through '>$169.99</h4>
          </div>
          <div className='flex justify-center'>
            <button className= 'btn my-3'> Add to Cart</button>
          </div>
        </div>

        </section>
      </div>
      
      </main>
    </>
  )

}